version: '3'

vars:
  COMPOSE: docker compose
  PHP82: n8n-bundle-php
  PHP84: n8n-bundle-php84

tasks:
  # Setup Development Environment
  init:
    desc: 'Initialize development environment'
    cmds:
      - task: up
      - task: composer:install
    aliases: ['i']

  composer:install:
    desc: 'Install composer dependencies'
    cmd: |
      docker exec {{ .PHP82 }} sh -c "
        if ! command -v composer > /dev/null 2>&1; then
          echo 'Installing Composer...'
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        fi
        composer install --no-interaction
      "
    aliases: ['install']

  # Docker Management
  up:
    desc: 'Start development environment (PHP 8.2 + 8.4)'
    cmd: '{{ .COMPOSE }} up -d'
    aliases: ['u']

  down:
    desc: 'Stop development environment'
    cmd: '{{ .COMPOSE }} down'
    aliases: ['d']

  restart:
    desc: 'Restart development environment'
    cmds:
      - task: down
      - task: up
    aliases: ['r']

  logs:
    desc: 'Show container logs'
    cmd: '{{ .COMPOSE }} logs -f'
    aliases: ['l']

  # Development Tasks
  shell:
    desc: 'Open shell in PHP 8.2 container'
    cmd: 'docker exec -it {{ .PHP82 }} sh'
    aliases: ['sh']

  shell84:
    desc: 'Open shell in PHP 8.4 container'
    cmd: 'docker exec -it {{ .PHP84 }} sh'

  serve:
    desc: 'Start development server'
    cmd: 'docker exec {{ .PHP82 }} php -S 0.0.0.0:8080 -t dev/'
    aliases: ['dev']

  # Testing
  test:
    desc: 'Run PHPUnit tests (PHP 8.2)'
    cmd: 'docker exec {{ .PHP82 }} vendor/bin/phpunit --testsuite=Unit'

  test:84:
    desc: 'Run PHPUnit tests (PHP 8.4)'
    cmd: 'docker exec {{ .PHP84 }} vendor/bin/phpunit --testsuite=Unit'

  test:coverage:
    desc: 'Run tests with coverage report'
    cmd: 'docker exec {{ .PHP82 }} vendor/bin/phpunit --testsuite=Unit --coverage-html=var/coverage'

  test:health:
    desc: 'Check application health'
    cmd: 'curl -X GET http://localhost:8080/demo/health'

  # Symfony Version Matrix Testing
  test:sf64:
    desc: 'Test with Symfony 6.4 (PHP 8.2)'
    cmd: |
      docker exec {{ .PHP82 }} sh -c "
        composer config extra.symfony.require '6.4.*' &&
        composer update --no-interaction --no-progress &&
        vendor/bin/phpunit --testsuite=Unit
      "

  test:sf71:
    desc: 'Test with Symfony 7.1 (PHP 8.2)'
    cmd: |
      docker exec {{ .PHP82 }} sh -c "
        composer config extra.symfony.require '7.1.*' &&
        composer update --no-interaction --no-progress &&
        vendor/bin/phpunit --testsuite=Unit
      "

  test:sf80:
    desc: 'Test with Symfony 8.0 (PHP 8.4)'
    cmd: |
      docker exec {{ .PHP84 }} sh -c "
        composer config extra.symfony.require '8.0.*' &&
        composer update --no-interaction --no-progress &&
        vendor/bin/phpunit --testsuite=Unit
      "

  test:matrix:
    desc: 'Run full test matrix (Symfony 6.4, 7.1, 8.0)'
    cmds:
      - task: test:sf64
      - task: test:sf71
      - task: test:sf80
      - cmd: |
          docker exec {{ .PHP82 }} composer config extra.symfony.require '^6.4|^7.0|^8.0'
        silent: true

  # Code Quality
  stan:
    desc: 'Run PHPStan analysis'
    cmd: 'docker exec {{ .PHP82 }} vendor/bin/phpstan analyse'

  cs:
    desc: 'Check code style'
    cmd: 'docker exec {{ .PHP82 }} vendor/bin/php-cs-fixer fix --dry-run --diff'

  cs:fix:
    desc: 'Fix code style'
    cmd: 'docker exec {{ .PHP82 }} vendor/bin/php-cs-fixer fix'
    aliases: ['fixer']

  default:
    desc: 'Show available commands'
    cmds:
      - task --list